### ISSUE TITLE
Move last updated into common area

### ISSUE THREAD

**Issue by bengro** [textbook/flash#13]
There is redundant information (= last updated) on the tiles that should be moved into the common area. Assuming we update all the services at the same time, there is little gain in keeping them separate for each tile.

Reducing redundancy will help make the design more focused.

**Comment by textbook** [comment]
As of 4adc833 I have removed it entirely from the UI but continued to send it in the responses; we can put it back in when and where appropriate.

**Comment by bengro** [comment]
Not sure this is still relevant.
