### ISSUE TITLE
Test helper to imitate different scenarios

### ISSUE THREAD

**Issue by bengro** [textbook/flash#20]
It would be great if we had a way to control the state of the services in order to render the UI in different states. This would help when styling the front-end.

Most important states are:
- A tile in an error state
- A tile in an ok state
- A pane item in a pending state
- A pane item in an ok state
- A pane item in an error state

**Comment by textbook** [comment]
Now every deployed Flash site has a route for testing CSS - see e.g. https://flash-goateed-validity.cfapps.pez.pivotal.io/scratchpad

**Comment by bengro** [comment]
Amazing! I will be using this soon!
