### ISSUE TITLE
Stacking services

### ISSUE THREAD

**Issue by bengro** [textbook/flash#22]
Services of the same type should be stacked.

An animation will help transition between the service tiles.

**Comment by textbook** [comment]
I've rearranged things a bit - the service-specific template partials (currently only for Tracker) and JavaScript now live in `flash_services`, and the boilerplate is here. Each service tile now includes `<service_name>-tile` so you can tell which are duplicates.

**Comment by bengro** [comment]
Great, thanks! I quickly added support for stacking tracker tiles, to get feedback early... there is still work needed for:
- Making sure stacking the tiles is not messing up the order of the services as appearing in config.json
- Generalising it to work with any service
- Better animations

**Comment by textbook** [comment]
It could do with some indication of how many services are stacked and which one we're on (e.g. _"X of Y"_, or filled-in dots like an image carousel). Also a less subtle transition, perhaps with a gentle colour pulse as it changes.

**Comment by textbook** [comment]
It might be nice to move the _"X of Y"_ notation up with the `.project-name`, to reduce the vertical space usage, e.g. `Gnome Design [2 of 2]`

**Comment by bengro** [comment]
I agree that your suggestion would further improve the stacking of services. Yet, I do not think it is worth additional work - as functionality-wise we would not gain much. I would wait for more user input and address stacking in next iteration of flash.

**Comment by textbook** [comment]
Very agile of you!
