### ISSUE TITLE
Current formatting only works on Safari

### ISSUE THREAD

**Issue by textbook** [textbook/flash#27]
The new CSS is broken on Chrome (and Firefox) but works fine on Safari.

**Chrome**:

<img width="1280" alt="chrome" src="https://cloud.githubusercontent.com/assets/785939/15275622/8fb41f5e-1ac8-11e6-8556-a4211c12a8bb.png">

**Safari**:

<img width="1280" alt="safari" src="https://cloud.githubusercontent.com/assets/785939/15275624/96c99814-1ac8-11e6-8249-2bfdb9963788.png">

**Comment by bengro** [comment]
See, #29. I have tested it for real with the latest chrome and firefox.
